### ISSUE TITLE
和插件 fluwx 冲突

### ISSUE THREAD

**Issue by kainy** [flutter-plugin/flutter-scheme#1]
影响了fluwx的使用 详见issue
https://github.com/OpenFlutter/fluwx/issues/398

**Comment by thesnail** [comment]
@kainy  感谢关注，[appscheme](https://pub.flutter-io.cn/packages/appscheme)获取了所有的scheme,如果你在其他插件中处理的有特定的scheme,建议在**registerSchemeListener**监听中做拦截处理，例如：

``` dart
appScheme.registerSchemeListener().listen((event) {
          if (event != null && event.path != '/xxx/oauth') {
          }
        });
```

后续将增加其他解决方案，感谢关注

**Comment by guotao** [comment]
> @kainy 感谢关注，[appscheme](https://pub.flutter-io.cn/packages/appscheme)获取了所有的scheme,如果你在其他插件中处理的有特定的scheme,建议在**registerSchemeListener**监听中做拦截处理，例如：
> 
> ```dart
> appScheme.registerSchemeListener().listen((event) {
>           if (event != null && event.path != '/xxx/oauth') {
>           }
>         });
> ```
> 
> 后续将增加其他解决方案，感谢关注

感谢解答，但是你这个是在dart代码，而这个问题只影响iOS，要做的应该是

`重写 AppDelegate 的 handleOpenURL 和 openURL 方法：



- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url {
    return  [WXApi handleOpenURL:url delegate:self];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    return [WXApi handleOpenURL:url delegate:self];
}`

咋写呢？
请升级到1.0.5版本，感谢关注
[```appscheme: ^1.0.5```](https://pub.flutter-io.cn/packages/appscheme/install)

**Comment by thesnail** [comment]
@guotao  [```appscheme: ^1.0.5```](https://pub.flutter-io.cn/packages/appscheme/install)

**Comment by kainy** [comment]
貌似还是不行， 运行完 pod install后

Installing appscheme (1.0.4)

pod里的appscheme版本还是104？

**Comment by kainy** [comment]
把

`[registrar addApplicationDelegate:instance];`

这一句注释掉，就没问题。

**Comment by thesnail** [comment]
> 貌似还是不行， 运行完 pod install后
> 
> Installing appscheme (1.0.4)
> 
> pod里的appscheme版本还是104？


进入flutter 项目中 使用 ```flutter pub upgrade```，这条指令升级,

**Comment by thesnail** [comment]
> 貌似还是不行， 运行完 pod install后
> 
> Installing appscheme (1.0.4)
> 
> pod里的appscheme版本还是104？

@kainy  使用
```
flutter pub upgrade
```
升级

**Comment by kainy** [comment]
> ```
> flutter pub upgrade
> ```

试了，还是一样，你看看 Podfile.lock 这个文件里面是不是1.0.4？ 难道是我电脑问题/

**Comment by thesnail** [comment]
@guotao @kainy  如果没有问题我先关闭了啊
